version: "3.9"

services:
  stoplightio_prism:
    container_name: ${PROJECT_NAME}_stoplightio_prism
    image: stoplight/prism:4
    # command: 'mock -d -h 0.0.0.0 /build/bff.yaml'  # with dynamic response generation (i.e. no examples)
    command: 'mock -h 0.0.0.0 /build/bff.yaml'
    volumes:
      - ./build/bff.yaml:/build/bff.yaml
    ports:
      # Serve the mocked API locally as available on port 8080
      - '8080:4010'
