openapi: 3.0.3
info:
  title: DEPRECATED! BFF-Auth - The Association for Cube Commons Canada

  # BEWARE: This is just a placeholder and will be set by the package publishing scripts.
  # In general, use semantic versioning: http://semver.org/
  version: '0.0.1'
  
  description: |
    # DEPRECATED! BFF-Auth (Authentication for Backend-for-Frontend)

    DEPRECATED! These endpoints are now found in bff.yaml

    The BFF-Auth API encapsulates authentication for the BFF.
    It's kept separate for modularity.

  contact:
    email: tech@cubecommons.ca
    url: https://github.com/cubeca
  license:
    name: UNLICENSED
    url: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#license

tags:
  - name: Auth
    description: Login, forgot password, etc.

servers:
  - url: https://bff-auth-{stage}.cubecommons.ca
    description: CUBE's shared API server instances, including production
    variables:
      stage:
        enum:
          # # DEV, UNSTABLE and STAGING are stages in the development environment
          - dev
          - unstable
          # - staging

          # # Both SANDBOX and LIVE are stages in the production environment
          # - sandbox
          # - live
        default: dev
        description: deployment stage

  - url: http://localhost:{port}
    description: Local development
    variables:
      port:
        enum:
          - '8084'
          - '18084'
        default: '8084'

paths:
  '/auth/anonymous':
    $ref: ./identity-microservice.yaml#/paths/~1auth~1anonymous
  '/auth/login':
    $ref: ./identity-microservice.yaml#/paths/~1auth~1login
  '/auth/user':
    $ref: ./identity-microservice.yaml#/paths/~1auth~1user
  '/auth/email':
    $ref: ./identity-microservice.yaml#/paths/~1auth~1email
  '/auth/password':
    $ref: ./identity-microservice.yaml#/paths/~1auth~1password
  '/auth/verify':
    $ref: ./identity-microservice.yaml#/paths/~1auth~1verify
  '/auth/forgot-password':
    $ref: ./identity-microservice.yaml#/paths/~1auth~1forgot-password

components:
  $ref: ./_partials/common-components.yaml

security:
  - jwt_logged_in: []
