openapi: 3.0.3
info:
  title: Profile - The Association for Cube Commons Canada\
  version: '0.0.1' # BEWARE: This is just a placeholder and will be set by the package publishing scripts.
  description: |
    # Profile APIs

    The Profile APIs are the custodian of Content Creator profiles.

  contact:
    email: tech@cubecommons.ca
    url: https://github.com/cubeca
  license:
    name: UNLICENSED
    url: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#license

tags:
  - name: Profile
    description: The Profile microservice is the custodian of Content Creator profiles.

security: 
  - jwt_logged_in: []

paths:
  '/profiles':
    get:
      operationId: get_profiles
      summary: Get all of the profiles
      description: Get all of the profiles
      tags:
        - Profile
      responses:
        '200':
          description: Profile details
          content:
            application/json:
              schema:
                $ref: ../schemas/profile/get_profile_response.json
              example:
                $ref: ../schemas/profile/get_profile_response.example.json
        '400':
          $ref: '#/components/responses/error400'
        '401':
          $ref: '#/components/responses/error401'
        '403':
          $ref: '#/components/responses/error403'
        '404':
          $ref: '#/components/responses/error404'
        '405':
          $ref: '#/components/responses/error405'
        '406':
          $ref: '#/components/responses/error406'
        '422':
          $ref: '#/components/responses/error422'
        '429':
          $ref: '#/components/responses/error429'
        '500':
          $ref: '#/components/responses/error500'
        '503':
          $ref: '#/components/responses/error503'
    post:
      operationId: create_profile
      summary: Create Profile
      description: Create Profile
      tags:
        - Profile
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../schemas/profile/create_profile_request.json
            example:
              $ref: ../schemas/profile/create_profile_request.example.json
        description: Create Profile Request
        required: true
      responses:
        '200':
          description: Create Profile Response
          content:
            application/json:
              schema:
                $ref: ../schemas/profile/create_profile_response.json
              example:
                $ref: ../schemas/profile/create_profile_response.example.json
        '400':
          $ref: '#/components/responses/error400'
        '401':
          $ref: '#/components/responses/error401'
        '403':
          $ref: '#/components/responses/error403'
        '404':
          $ref: '#/components/responses/error404'
        '405':
          $ref: '#/components/responses/error405'
        '406':
          $ref: '#/components/responses/error406'
        '422':
          $ref: '#/components/responses/error422'
        '429':
          $ref: '#/components/responses/error429'
        '500':
          $ref: '#/components/responses/error500'
        '503':
          $ref: '#/components/responses/error503'

  '/profiles/{profileId}':
    parameters:
      - name: profileId
        in: path
        description: Profile ID
        required: true
        schema:
          type: string
          format: uuid
    get:
      operationId: get_profile
      summary: Get profile details
      description: Get profile details.
      tags:
        - Profile
      responses:
        '200':
          description: Profile details
          content:
            application/json:
              schema:
                $ref: ../schemas/profile/get_profile_response.json
              example:
                $ref: ../schemas/profile/get_profile_response.example.json
        '400':
          $ref: '#/components/responses/error400'
        '401':
          $ref: '#/components/responses/error401'
        '403':
          $ref: '#/components/responses/error403'
        '404':
          $ref: '#/components/responses/error404'
        '405':
          $ref: '#/components/responses/error405'
        '406':
          $ref: '#/components/responses/error406'
        '422':
          $ref: '#/components/responses/error422'
        '429':
          $ref: '#/components/responses/error429'
        '500':
          $ref: '#/components/responses/error500'
        '503':
          $ref: '#/components/responses/error503'
    patch:
      operationId: update_profile
      summary: Update Profile
      description: Update Profile.
      tags:
        - Profile   
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../schemas/profile/update_profile_request.json
            example:
              $ref: ../schemas/profile/update_profile_request.example.json
        description: Profile Update
        required: true
      responses:
        '200':
          description: Update Profile Response
          content:
            application/json:
              schema:
                $ref: ../schemas/profile/update_profile_response.json
              example:
                $ref: ../schemas/profile/update_profile_response.example.json
        '400':
          $ref: '#/components/responses/error400'
        '401':
          $ref: '#/components/responses/error401'
        '403':
          $ref: '#/components/responses/error403'
        '404':
          $ref: '#/components/responses/error404'
        '405':
          $ref: '#/components/responses/error405'
        '406':
          $ref: '#/components/responses/error406'
        '422':
          $ref: '#/components/responses/error422'
        '429':
          $ref: '#/components/responses/error429'
        '500':
          $ref: '#/components/responses/error500'
        '503':
          $ref: '#/components/responses/error503'
    delete:
      operationId: delete_profile
      summary: Delete profile
      description: Delete profile details
      tags:
        - Profile
      responses:
        '200':
          description: Delete a profile
          content:
            application/json:
              schema:
                $ref: ../schemas/profile/delete_profile_response.json
              example:
                $ref: ../schemas/profile/delete_profile_response.example.json
        '400':
          $ref: '#/components/responses/error400'
        '401':
          $ref: '#/components/responses/error401'
        '403':
          $ref: '#/components/responses/error403'
        '404':
          $ref: '#/components/responses/error404'
        '405':
          $ref: '#/components/responses/error405'
        '406':
          $ref: '#/components/responses/error406'
        '422':
          $ref: '#/components/responses/error422'
        '429':
          $ref: '#/components/responses/error429'
        '500':
          $ref: '#/components/responses/error500'
        '503':
          $ref: '#/components/responses/error503'
  '/profiles/tag/{tag}':
    parameters:
      - name: tag
        in: path
        description: Profile tag
        required: true
        schema:
          type: string
    get:
      operationId: get_profile_by_tag
      summary: Get profile details by tag
      description: Get profile details by tag.
      tags:
        - Profile
      responses:
        '200':
          description: Profile details
          content:
            application/json:
              schema:
                $ref: ../schemas/profile/get_profile_response.json
              example:
                $ref: ../schemas/profile/get_profile_response.example.json
        '400':
          $ref: '#/components/responses/error400'
        '401':
          $ref: '#/components/responses/error401'
        '403':
          $ref: '#/components/responses/error403'
        '404':
          $ref: '#/components/responses/error404'
        '405':
          $ref: '#/components/responses/error405'
        '406':
          $ref: '#/components/responses/error406'
        '422':
          $ref: '#/components/responses/error422'
        '429':
          $ref: '#/components/responses/error429'
        '500':
          $ref: '#/components/responses/error500'
        '503':
          $ref: '#/components/responses/error503'
  '/getProfilesByIdList':
    post:
      operationId: getProfilesByIdList
      summary: get a list of profiles by id list
      description: get a list of profiles by id list
      tags:
        - Profile
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../schemas/profile/get_profiles_by_id_list_request.json
            example:
              $ref: ../schemas/profile/get_profiles_by_id_list_request.example.json
        description: Get profiles by id list request
        required: true
      responses:
        '200':
          description: Get profiles by id list response
          content:
            application/json:
              schema:
                $ref: ../schemas/profile/get_profiles_by_id_list_response.json
              example:
                $ref: ../schemas/profile/get_profiles_by_id_list_response.example.json
        '400':
          $ref: '#/components/responses/error400'
        '401':
          $ref: '#/components/responses/error401'
        '403':
          $ref: '#/components/responses/error403'
        '404':
          $ref: '#/components/responses/error404'
        '405':
          $ref: '#/components/responses/error405'
        '406':
          $ref: '#/components/responses/error406'
        '422':
          $ref: '#/components/responses/error422'
        '429':
          $ref: '#/components/responses/error429'
        '500':
          $ref: '#/components/responses/error500'
        '503':
          $ref: '#/components/responses/error503'
  '/search':
    get:
      operationId: search
      summary: Search based on query parameters
      description: Returns search results based on the provided query parameters.
      tags:
        - Profile
      parameters:
        - name: offset
          in: query
          description: Offset into the result set
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          description: Max number of items to return
          required: false
          schema:
            type: integer
        - name: searchTerm
          in: query
          description: term to look for in data
          required: true
          schema:
            type: string
      responses:
        '200':
          description: search results
          content:
            application/json:
              schema:
                $ref: ../schemas/profile/storage_list.json
              example:
                $ref: ../schemas/profile/storage_list.example.json
        '400':
          $ref: '#/components/responses/error400'
        '401':
          $ref: '#/components/responses/error401'
        '403':
          $ref: '#/components/responses/error403'
        '404':
          $ref: '#/components/responses/error404'
        '405':
          $ref: '#/components/responses/error405'
        '406':
          $ref: '#/components/responses/error406'
        '422':
          $ref: '#/components/responses/error422'
        '429':
          $ref: '#/components/responses/error429'
        '500':
          $ref: '#/components/responses/error500'
        '503':
          $ref: '#/components/responses/error503'

components:
  responses:
    success200:
      $ref: './_partials/common-components.yaml#/responses/success200'
    error400:
      $ref: './_partials/common-components.yaml#/responses/error400'
    error401:
      $ref: './_partials/common-components.yaml#/responses/error401'
    error403:
      $ref: './_partials/common-components.yaml#/responses/error403'
    error404:
      $ref: './_partials/common-components.yaml#/responses/error404'
    error405:
      $ref: './_partials/common-components.yaml#/responses/error405'
    error406:
      $ref: './_partials/common-components.yaml#/responses/error406'
    error422:
      $ref: './_partials/common-components.yaml#/responses/error422'
    error429:
      $ref: './_partials/common-components.yaml#/responses/error429'
    error500:
      $ref: './_partials/common-components.yaml#/responses/error500'
    error503:
      $ref: './_partials/common-components.yaml#/responses/error503'

  securitySchemes:
    jwt_logged_in:
      $ref: './_partials/common-components.yaml#/securitySchemes/jwt_logged_in'
