name: Publish API client NPM package to npm.pkg.github.com

run-name: Publish commit ${{ github.sha }} of API client NPM package to npm.pkg.github.com

on: push

env:
  GITHUB_SHA: ${{ github.sha }}

jobs:
  publish_package_job:
    runs-on: ubuntu-22.04
    name: Publish API client NPM package to npm.pkg.github.com
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v2

      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: "Run make ci_gha"
        run: |
          make ci_gha

      # - name: Switch to GPR (Github Package Registry) at npm.pkg.github.com
      #   uses: actions/setup-node@v3
      #   with:
      #     registry-url: 'https://npm.pkg.github.com'
      #     scope: "@${{ env.GITHUB_REPOSITORY_OWNER }}"

      - name: Publish to npm.pkg.github.com
        run: |
          cd ./build/gen/typescript-axios
          LATEST=`npm view . version 2>/dev/null || echo "0"`
          echo "LATEST==$LATEST"
          CURRENT=`cat package.json | jq -r .version`
          echo "CURRENT==$CURRENT"
          if [ "$LATEST" != "$CURRENT" ]
          then
              npm install
              npm run build
              npm config set @cubeca:registry https://npm.pkg.github.com/cubeca
              npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
