name: Publish API client NPM package to npm.pkg.github.com

run-name: Publish API client NPM package @ ${{ github.sha }}

on: push

env:
  GITHUB_SHA: ${{ github.sha }}

jobs:
  publish_package:
    runs-on: ubuntu-22.04
    name: Publish API client NPM package to npm.pkg.github.com
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v2

      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: "Run make ci_gha"
        run: |
          make ci_gha

      - name: "Switch to GPR (Github Packages Registry) at npm.pkg.github.com for all @${{ github.repository_owner }}/* packages"
        run: |
          ./scripts/write_npmrc.sh bff '${{ secrets.GITHUB_TOKEN }}' '${{ github.repository_owner }}'
          ./scripts/write_npmrc.sh bff-auth '${{ secrets.GITHUB_TOKEN }}' '${{ github.repository_owner }}'

      - name: Publish to npm.pkg.github.com
        run: |
          ./scripts/publish.sh bff
          ./scripts/publish.sh bff-auth
